//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture_K.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keys
    {
        public int idKeys { get; set; }
        public int idBuyer { get; set; }
        public int idConttract { get; set; }
        public int idModel { get; set; }
        public int idSale { get; set; }
        public int idSpecificationsModel { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Model Model { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual SpecificationsModel SpecificationsModel { get; set; }
    }
}
